version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "YES"
      SA_PASSWORD: "Docker2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  cart-api:
    build: .
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Docker2021"
      DatabaseName: "applicationdb"
    ports:
      - "8090:80"